export const videoTypes = {
  GET_ALL_VIDEOS: 'GET_ALL_VIDEOS', 
  GET_ALL_VIDEOS_SUCCESS: 'GET_ALL_VIDEOS_SUCCESS', 
  GET_ALL_VIDEOS_ERROR: 'GET_ALL_VIDEOS_ERROR' ,
  IS_LOADING_VIDEOS: 'IS_LOADING_VIDEOS',

  
};